services:
  foi2026.warehouseflow.web:
    image: ${DOCKER_REGISTRY-}foi2026warehouseflowweb
    build:
      context: .
      dockerfile: FOI2026.WarehouseFlow.Web/Dockerfile
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
